### ISSUE TITLE
Support TYPO3 13

### ISSUE THREAD

**Issue by nebrot** [WapplerSystems/save_and_close#3]
We have tested current branch with TYPO3 13.0.0. With this changes it works for our config:

Change version to to `^12.4 || ^13.0`
https://github.com/WapplerSystems/save_and_close/blob/5ce7db16cb01333e3e1f3fb693fa90d52aaefde5/composer.json#L25

Change version to to `12.4.0-13.4.99`
https://github.com/WapplerSystems/save_and_close/blob/5ce7db16cb01333e3e1f3fb693fa90d52aaefde5/ext_emconf.php#L14

Perhaps change deprecated constants (only TYPO3 13?!), see: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Deprecation-101475-IconSizeStringConstants.html#deprecation-101475-icon-size-string-constants

After upgrading to TYPO3 13.1.0 it's not working anymore, perhaps because of new hotkey https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103529-IntroduceHotkeyForSaveAndClose.html#feature-103529-introduce-hotkey-for-save-and-close ?

**Comment by gmartino27** [comment]
Also played around and don't found a solution..

Like @nebrot wrote, seems to be related to this:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103529-IntroduceHotkeyForSaveAndClose.html#feature-103529-introduce-hotkey-for-save-and-close

Somebody some ideas how we can bring it to work again for TYPO3 ^13.1.0 ??

**Comment by svewap** [comment]
Sadly, in my current estimation, it is not possible to implement a save-and-close in vendor/typo3/cms-backend/Classes/Controller/EditDocumentController.php, because when the close parameter is set, in line 467 an exit takes place immediately and saving no longer occurs.
I therefore currently only see the change in overloading and modifying the complete class.
What do you think?
I have pushed my status into the release/v13 branch.
```
// Close document if a request for closing the document has been sent
if ($this->closeDoc > self::DOCUMENT_CLOSE_MODE_DEFAULT) {
    if ($response = $this->closeDocument($this->closeDoc, $request)) {
        return $response;
    }
}
```

**Comment by nebrot** [comment]
I would prefer to not overloading/modifiying the [complete class](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Controller/EditDocumentController.php), seems to be huge and could cause other problems after core-updates.

Do you know which specific core change made it impossible to follow the previous path as in v12? Perhaps we should inform the coredevs that this custom solution doesn't work anymore with current 13.3 and probably 13 LTS next week.

There are many discussions after removing the core solution:
- https://forge.typo3.org/issues/87812
- https://forge.typo3.org/issues/95515

**Comment by svewap** [comment]
Thanks for the feedback and the references to the discussions. I'm surprised that the hotkey is supposed to work.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103529-IntroduceHotkeyForSaveAndClose.html
 I'll have to look into it again.

**Comment by Mainbird** [comment]
Hi :)

you can also add some js to make it work again.

1. Add a custom JavaScript module

example/Configuration/JavaScriptModules.php
```
<?php

return [
    'dependencies' => ['backend'],
    'tags' => [
        'backend.form',
    ],
    'imports' => [
        '@vendor/example/' => 'EXT:example/Resources/Public/JavaScript/Backend/',
    ],
];
```

example/Resources/Public/JavaScript/Backend/SaveAndClose.js
```
import FormEngine from '@typo3/backend/form-engine.js'

class SaveAndClose {
  constructor () {
   // I have added the data-js attribute to the button so I can select it like that
    this.button = document.querySelector('[data-js=save-and-close-button]')
    this.#addEvents()
  }

  #addEvents () {
    this.button?.addEventListener('click', (e) => {
      e.preventDefault()
      FormEngine.saveAndCloseDocument()
    })
  }
}

export default new SaveAndClose()
```

2. Modify the event to load custom js module as well

```
<?php

declare(strict_types=1);

namespace Vendor\Example\EventListener;

use TYPO3\CMS\Backend\Template\Components\ButtonBar;
use TYPO3\CMS\Backend\Template\Components\Buttons\InputButton;
use TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent;
use TYPO3\CMS\Core\Imaging\Icon;
use TYPO3\CMS\Core\Imaging\IconFactory;
use TYPO3\CMS\Core\Localization\LanguageService;
use TYPO3\CMS\Core\Page\PageRenderer;
use TYPO3\CMS\Core\Utility\GeneralUtility;

final class SaveCloseButtonEventListener
{
    public function __invoke(ModifyButtonBarEvent $event): void
    {
        $buttons = $event->getButtons();
        $buttonBar = $event->getButtonBar();
        $saveButton = $buttons[ButtonBar::BUTTON_POSITION_LEFT][2][0] ?? null;

        if ($saveButton instanceof InputButton) {
            $iconFactory = GeneralUtility::makeInstance(IconFactory::class);
            $language = $this->getLanguageService();
            $title = $language ? $language->sL(
                'LLL:EXT:core/Resources/Private/Language/locallang_core.xlf:rm.saveCloseDoc'
            ) : 'save';

            $saveCloseButton = $buttonBar->makeInputButton()
                ->setName('_saveandclosedok')
                ->setValue('1')
                ->setForm($saveButton->getForm())
                ->setDataAttributes([
                    'js' => 'save-and-close-button',
                ])
                ->setTitle($title)
                ->setIcon($iconFactory->getIcon('actions-document-save-close', Icon::SIZE_SMALL))
                ->setShowLabelText(true);

            $buttons[ButtonBar::BUTTON_POSITION_LEFT][2][] = $saveCloseButton;
        }

        /** @var PageRenderer $pageRenderer */
        $pageRenderer = GeneralUtility::makeInstance(PageRenderer::class);
        $pageRenderer->loadJavaScriptModule('@vendor/example/SaveAndClose.js');

        $event->setButtons($buttons);
    }

    protected function getLanguageService(): ?LanguageService
    {
        return $GLOBALS['LANG'];
    }
}
```

I dont know if this is great or not, but it works like a charm for me so far :)

**Comment by svewap** [comment]
Thank you very much. I have tested the code and have just released a new version for the 13.
